# Generated by Django 4.1.2 on 2022-11-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ваня', max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('description', models.TextField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='core.director')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.movie')),
            ],
        ),
    ]
